name: Test file changes
on:
  push:
    branches:
      - master
  pull_request:
      types: closed
  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v33
        with:
          separator: ','
      - name: Log changed files
        run: |
          echo "added: ${{ steps.changed-files.outputs.added_files }}"
          echo "copied: ${{ steps.changed-files.outputs.copied_files }}"
          echo "deleted: ${{ steps.changed-files.outputs.deleted_files }}"
          echo "modified: ${{ steps.changed-files.outputs.modified_files }}"
          echo "renamed: ${{ steps.changed-files.outputs.renamed_files }}"